version: 0.0
os: linux

spring:
  mvc:
    throw-exception-if-no-handler-found: true
files:
  - source: /
    destination: /home/ubuntu/drcloud-deploy
permissions:
  - object: /home/ubuntu/drcloud-deploy
    owner: ubuntu
    group: ubuntu
    mode: 755
