spring:
  application:
    name: Krush2

---
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/team2
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_USERNAME}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql : true
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQLDialect
